apiVersion: k8s.nginx.org/v1
kind: VirtualServerRoute
metadata:
  name: {{.Values.frontend.uiPath}}
spec:
  host: {{.Values.host}}
  upstreams:
  - name: {{.Values.frontend.uiPath}}
    service: {{.Values.frontend.uiPath}}
    port: 80
  subroutes:
  - path: /{{.Values.frontend.uiPath}}
    action:
      proxy:
        upstream: {{.Values.frontend.uiPath}}
        rewritePath: /
---
apiVersion: k8s.nginx.org/v1
kind: VirtualServerRoute
metadata:
  name: {{.Values.name}}
spec:
  host: {{.Values.host}}
  upstreams:
  - name: {{.Values.stableName}}
    service: {{.Values.stableName}}
    port: 80
  - name: {{.Values.canaryName}}
    service: {{.Values.canaryName}}
    port: 80
  subroutes:
  - path: /{{.Values.stableName}}
    action:
      proxy:
        upstream: {{.Values.stableName}}
        rewritePath: /{{.Values.name}}/index.html
  - path: /{{.Values.canaryName}}
    action:
      proxy:
        upstream: {{.Values.canaryName}}
        rewritePath: /{{.Values.name}}/index.html
  - path: /{{.Values.name}}
    {{- if .Values.splitTraffic}}
    splits:
    - weight: {{.Values.stableWeight}}
      action:
        proxy:
          upstream: {{.Values.stableName}}
          rewritePath: /{{.Values.name}}/index.html
    - weight: {{.Values.canaryWeight}}
      action:
        proxy:
          upstream: {{.Values.canaryName}}
          rewritePath: /{{.Values.name}}/index.html
    {{- else}}
    action:
      proxy:
        upstream: {{.Values.stableName}}
        rewritePath: /{{.Values.name}}/index.html
    {{- end}}