name: color
canaryName: color-canary
stableName: color-stable
host: nginx-demo.harness.io
image: <+artifact.image>
splitTraffic: false

replicas: 2
namespace: <+infra.namespace>

frontend:
  uiPath: canary
  title: Canary - Nginx Traffic Shift
  image: us.gcr.io/sales-209522/continuous-requests:110
