name: color
canaryName: color-canary
stableName: color-stable
host: nginx-demo.harness.io
image: <+artifact.image>
splitTraffic: false

replicas: 2
namespace: <+infra.namespace>

frontend:
  uiPath: canary
  title: Canary - Nginx Traffic Shift
  image: us-docker.pkg.dev/sales-209522/demo/continuous-requests:100
