name: <+serviceVariables.name>
image: <+artifact.image>
canaryName: <+serviceVariables.canaryName>
stableName: <+serviceVariables.stableName>
endpoint: color
canaryEndpoint: color-canary
stableEndpoint: color-stable
splitTraffic: false

replicas: 2
namespace: <+infra.namespace>

frontend:
  title: Canary - Nginx Traffic Shift
  loadBalancer: <+serviceVariables.loadBalancer>
  ui: <+serviceVariables.ui>
  image: us.gcr.io/sales-209522/continuous-requests:110
